[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shared-accounts"
version = "0.1.0"
dependencies = ["Django>=4.2"]

[tool.setuptools.packages.find]
where = ["."]
include = ["accounts"]